"""
LLM Router — LiteLLM wrapper with fallback chain + mock provider.

Design rules (per project spec):
  - Each agent = ONE LLM call with bounded input.
  - Fallback chain per agent: try primary, then fallback, then fallback_2.
  - If all fail AND allow_mock=true, return a deterministic mock so dev
    never blocks on a missing API key.
  - Token cost is predictable because there is no chatter — exactly one
    successful call per agent per invocation.

The router is the ONLY place that knows about LiteLLM. Agents import
`route()` and get back a string.
"""
from __future__ import annotations

import hashlib
import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml
from dotenv import load_dotenv

load_dotenv()

# Lazy import — litellm is heavy and we want graceful failure if missing
try:
    import litellm  # type: ignore
    _HAS_LITELLM = True
except ImportError:
    litellm = None  # type: ignore
    _HAS_LITELLM = False


@dataclass
class AgentConfig:
    name: str
    role: str
    primary: str
    fallback: str | None = None
    fallback_2: str | None = None
    system_prompt_file: str | None = None
    temperature: float = 0.2
    max_tokens: int = 2048
    allow_mock: bool = True
    needs_tools: list[str] | None = None


def load_agents(path: str = "config/agents.yaml") -> dict[str, AgentConfig]:
    with open(path, "r", encoding="utf-8") as f:
        spec = yaml.safe_load(f)
    out: dict[str, AgentConfig] = {}
    for name, a in spec.get("agents", {}).items():
        model = a.get("model", {})
        out[name] = AgentConfig(
            name=name,
            role=a.get("role", ""),
            primary=model.get("primary", ""),
            fallback=model.get("fallback"),
            fallback_2=model.get("fallback_2"),
            system_prompt_file=a.get("system_prompt_file"),
            temperature=a.get("temperature", 0.2),
            max_tokens=a.get("max_tokens", 2048),
            allow_mock=a.get("allow_mock", True),
            needs_tools=a.get("needs_tools"),
        )
    return out


def _load_prompt(path: str) -> str:
    p = Path(path)
    if not p.exists():
        return ""
    return p.read_text(encoding="utf-8")


def _mock_response(agent: str, prompt: str, role: str) -> str:
    """Deterministic mock — same prompt always yields same output.

    This is the safety net that lets the DAG run end-to-end with zero
    API keys configured. Production runs will use real models.
    """
    h = hashlib.sha256(f"{agent}|{prompt}".encode()).hexdigest()[:8]
    if agent == "thinker":
        return (
            "# Plan\n\n"
            "Generated by mock thinker (configure a real model in config/agents.yaml).\n\n"
            "## Task T1\n"
            "- id: T1\n- title: Implement the goal\n- needs_research: true\n"
            f"- description: First task — researcher will try to web-ground this.\n"
            f"- hash: {h}\n\n"
            "## Task T2\n"
            "- id: T2\n- title: Add tests\n- needs_research: false\n"
            f"- hash: {h}\n"
        )
    if agent == "coder":
        return (
            f"// mock coder output (hash {h})\n"
            f"// role: {role}\n\n"
            "```python path=src/hello.py\n"
            "def hello():\n"
            "    return 'hello from myforge'\n"
            "```\n\n"
            "```python path=tests/test_hello.py\n"
            "from src.hello import hello\n"
            "def test_hello():\n"
            "    assert hello() == 'hello from myforge'\n"
            "```\n"
        )
    if agent == "reviewer":
        return "STATUS: approved\n\nNo defects found. (mock reviewer)\n"
    if agent == "bugfixer":
        return "// mock bugfixer: applied reviewer notes (no-op)\n"
    if agent == "researcher":
        return (
            f"# Research: {h}\n\n"
            "## Summary\n\n"
            "(mock researcher) No external sources — TAVILY_API_KEY not set or "
            "no results returned. Notes below are from the model's own knowledge.\n\n"
            "## Findings\n\n"
            "- No web sources were available for this task.\n\n"
            "## Recommendations for the coder\n\n"
            "- Proceed using existing repo context.\n"
            "- If the task genuinely requires external info, set TAVILY_API_KEY "
            "and re-run.\n"
        )
    return f"[mock {agent}] {role}"


def _call_litellm(model: str, system: str, prompt: str,
                  temperature: float, max_tokens: int) -> str:
    """Single LiteLLM call. Raises on failure."""
    if not _HAS_LITELLM:
        raise RuntimeError("litellm not installed")
    messages = [
        {"role": "system", "content": system},
        {"role": "user", "content": prompt},
    ]
    resp = litellm.completion(
        model=model,
        messages=messages,
        temperature=temperature,
        max_tokens=max_tokens,
    )
    content = resp.choices[0].message.content  # type: ignore
    if isinstance(content, str):
        if content.strip():
            try:
                parsed = json.loads(content)
            except json.JSONDecodeError:
                parsed = None
            if isinstance(parsed, dict) and "tool" in parsed:
                raise ValueError(f"{model} returned unsupported tool-call JSON")
            return content
        raise ValueError(f"{model} returned empty message content")
    if isinstance(content, list):
        text_parts = [
            part.get("text", "")
            for part in content
            if isinstance(part, dict) and part.get("type") == "text"
        ]
        text = "\n".join(p for p in text_parts if p)
        if text.strip():
            return text
    raise ValueError(f"{model} returned no text content")


def _log_fallback(agent: str, model_tried: str, err: Exception,
                  next_label: str | None) -> None:
    """Append a fallback event to logs/router.log so users can see which
    model in the chain succeeded and which failed.

    This is the Phase 5 'model fallback logging' requirement.
    """
    from pathlib import Path
    import time
    log_path = Path("logs/router.log")
    log_path.parent.mkdir(parents=True, exist_ok=True)
    next_msg = f" -> trying {next_label}" if next_label else " -> no more fallbacks"
    with log_path.open("a", encoding="utf-8") as f:
        f.write(
            f"[{time.strftime('%Y-%m-%dT%H:%M:%S')}] "
            f"agent={agent} model={model_tried} failed: "
            f"{type(err).__name__}: {err}{next_msg}\n"
        )


def _log_success(agent: str, model: str, is_mock: bool) -> None:
    from pathlib import Path
    import time
    log_path = Path("logs/router.log")
    log_path.parent.mkdir(parents=True, exist_ok=True)
    kind = "MOCK" if is_mock else "LIVE"
    with log_path.open("a", encoding="utf-8") as f:
        f.write(
            f"[{time.strftime('%Y-%m-%dT%H:%M:%S')}] "
            f"agent={agent} model={model} OK ({kind})\n"
        )


def route(agent_name: str, prompt: str,
          agents: dict[str, AgentConfig] | None = None,
          extra_context: str = "") -> str:
    """Run one agent. Returns the model's text output.

    Tries primary -> fallback -> fallback_2 -> mock (if allowed).
    Never raises (unless allow_mock=False and all providers fail).
    Logs every attempt to logs/router.log so fallback chains are auditable.
    """
    if agents is None:
        agents = load_agents()
    cfg = agents.get(agent_name)
    if cfg is None:
        raise KeyError(f"unknown agent: {agent_name}")

    system = _load_prompt(cfg.system_prompt_file) if cfg.system_prompt_file else cfg.role
    if extra_context:
        system = f"{system}\n\n## Context\n{extra_context}"

    chain = [
        ("primary", cfg.primary),
        ("fallback", cfg.fallback),
        ("fallback_2", cfg.fallback_2),
    ]
    last_err: Exception | None = None
    for i, (label, model) in enumerate(chain):
        if not model:
            continue
        try:
            out = _call_litellm(
                model=model,
                system=system,
                prompt=prompt,
                temperature=cfg.temperature,
                max_tokens=cfg.max_tokens,
            )
            _log_success(agent_name, model, is_mock=False)
            return out
        except Exception as e:  # noqa: BLE001
            last_err = e
            next_label = chain[i + 1][0] if i + 1 < len(chain) else None
            _log_fallback(agent_name, model, e, next_label)
            continue

    if cfg.allow_mock:
        _log_success(agent_name, "mock", is_mock=True)
        return _mock_response(agent_name, prompt, cfg.role)
    raise RuntimeError(
        f"agent {agent_name}: all providers failed and mock disabled. last_err={last_err}"
    )
